
PIATTI_DATA = [
    {"id": 1, "nome": "Pasta pomodoro e mozzarella", "proteina": "latticini", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 2, "nome": "Pasta pomodoro e tonno", "proteina": "pesce", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 3, "nome": "Pasta zucchine e gamberetti", "proteina": "pesce", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 4, "nome": "Pasta zucchine e ricotta", "proteina": "latticini", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 5, "nome": "Pasta al sugo di pesce", "proteina": "pesce", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 6, "nome": "Pasta al pesto e parmigiano", "proteina": "latticini", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 7, "nome": "Spaghetti alla carbonara light", "proteina": "uova", "stagione": "generico", "tempo": 35, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 8, "nome": "Gnocchi alla carrettiera", "proteina": "latticini", "stagione": "generico", "tempo": 45, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 9, "nome": "Ravioli cinesi", "proteina": "carne rossa", "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 10, "nome": "Pasta alle vongole", "proteina": "pesce", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 11, "nome": "Couscous alle verdure e pollo", "proteina": "carne bianca", "stagione": "estate", "tempo": 60, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 12, "nome": "Riso alla cantonese", "proteina": "uova", "stagione": "generico", "tempo": 40, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 13, "nome": "Riso alla cantonese", "proteina": "carne rossa", "stagione": "generico", "tempo": 40, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 14, "nome": "Risotto agli asparagi e formaggio", "proteina": "latticini", "stagione": "mezza stagione", "tempo": 40, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 15, "nome": "Insalata di riso con formaggio", "proteina": "latticini", "stagione": "estate", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 16, "nome": "Insalata di riso con tonno", "proteina": "pesce", "stagione": "estate", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 17, "nome": "Insalata di riso con prosciutto cotto", "proteina": "carne rossa", "stagione": "estate", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 18, "nome": "Risotto zafferano e salsiccia", "proteina": "carne rossa", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 19, "nome": "Risotto zafferano e stracchino", "proteina": "latticini", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 20, "nome": "Risotto zucchine e gorgonzola", "proteina": "latticini", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 21, "nome": "Risotto zucchine e gamberetti", "proteina": "pesce", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 22, "nome": "Pasta e fagioli", "proteina": "legumi", "stagione": "inverno", "tempo": 45, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 23, "nome": "Risotto al pomodoro e formaggio", "proteina": "latticini", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 24, "nome": "Pasta alla puttanesca", "proteina": "pesce", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 25, "nome": "Risotto zucca e gorgonzola", "proteina": "latticini", "stagione": "mezza stagione", "tempo": 45, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 26, "nome": "Risotto zucca e salsiccia", "proteina": "carne rossa", "stagione": "mezza stagione", "tempo": 45, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 27, "nome": "Risotto ai funghi e formaggio", "proteina": "latticini", "stagione": "generico", "tempo": 60, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 28, "nome": "Risotto ai funghi e salsiccia", "proteina": "carne rossa", "stagione": "generico", "tempo": 60, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 29, "nome": "Risotto al pesce", "proteina": "pesce", "stagione": "generico", "tempo": 70, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 30, "nome": "Cannelloni ricotta e spinaci", "proteina": "latticini", "stagione": "generico", "tempo": 70, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 31, "nome": "Zuppa di legumi", "proteina": "legumi", "stagione": "inverno", "tempo": 45, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 32, "nome": "Minestrone con formaggio", "proteina": "latticini", "stagione": "inverno", "tempo": 45, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 33, "nome": "Vellutata con formaggio", "proteina": "latticini", "stagione": "inverno", "tempo": 45, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 34, "nome": "Minestrina con il formaggio", "proteina": "latticini", "stagione": "inverno", "tempo": 15, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 35, "nome": "Minestra del prete", "proteina": "uova", "stagione": "inverno", "tempo": 15, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 36, "nome": "Tortellini in brodo", "proteina": "carne rossa", "stagione": "inverno", "tempo": 15, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 37, "nome": "Pappa al pomodoro e formaggio", "proteina": "latticini", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 38, "nome": "Pasta zafferano, speck e zucchine", "proteina": "carne rossa", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 39, "nome": "Pasta al salmone", "proteina": "pesce", "stagione": "generico", "tempo": 35, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 40, "nome": "Pasta gamberetti zucchine e zafferano", "proteina": "pesce", "stagione": "generico", "tempo": 40, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 41, "nome": "Pasta in bianco con il formaggio", "proteina": "latticini", "stagione": "generico", "tempo": 25, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 42, "nome": "Pomodori ripieni di riso", "proteina": "latticini", "stagione": "generico", "tempo": 70, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 43, "nome": "Zuppa verza e fagioli (farinata) con formaggio", "proteina": "latticini", "stagione": "inverno", "tempo": 120, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 44, "nome": "Ravioli ricotta e spinaci al pomodoro", "proteina": "latticini", "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "primo"},
    {"id": 45, "nome": "Pasta pomodoro piselli e formaggio", "proteina": "latticini", "stagione": "generico", "tempo": 35, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 46, "nome": "Pasta pomodorini e stracchino", "proteina": "latticini", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 47, "nome": "Pasta crema di peperoni e ricotta", "proteina": "latticini", "stagione": "generico", "tempo": 70, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 48, "nome": "Pasta crema di zucchine e burrata", "proteina": "latticini", "stagione": "generico", "tempo": 45, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 49, "nome": "Gnocchi porro e gamberi", "proteina": "pesce", "stagione": "generico", "tempo": 40, "adatto_al_lavoro": False, "tipologia": "primo"},
    {"id": 50, "nome": "Farro pomodoro mozzarella e olive", "proteina": "latticini", "stagione": "estate", "tempo": 45, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 51, "nome": "Piadina pomodoro mozzarella e crudo", "proteina": "carne rossa", "stagione": "generico", "tempo": 15, "adatto_al_lavoro": False, "tipologia": "unico"},
    {"id": 52, "nome": "Piadina pomodoro mozzarella e crudo", "proteina": "latticini", "stagione": "generico", "tempo": 15, "adatto_al_lavoro": False, "tipologia": "unico"},
    {"id": 53, "nome": "Burrito di carne", "proteina": "carne rossa", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "unico"},
    {"id": 54, "nome": "Burrito di carne", "proteina": "carne bianca", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "unico"},
    {"id": 55, "nome": "Pizza margherita", "proteina": "latticini", "stagione": "generico", "tempo": 15, "adatto_al_lavoro": False, "tipologia": "unico"},
    {"id": 56, "nome": "Panzanella con formaggio", "proteina": "latticini", "stagione": "estate", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 57, "nome": "Panzanella con tonno", "proteina": "pesce", "stagione": "estate", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 58, "nome": "Panzanella con carne", "proteina": "carne bianca", "stagione": "estate", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 59, "nome": "Fajitas di pollo", "proteina": "carne bianca", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": False, "tipologia": "unico"},
    {"id": 60, "nome": "Sushi", "proteina": "pesce", "stagione": "generico", "tempo": 1, "adatto_al_lavoro": False, "tipologia": "unico"},
    {"id": 61, "nome": "Insalata ceci tonno e olive", "proteina": "pesce", "stagione": "estate", "tempo": 15, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 62, "nome": "Insalata ceci tonno e olive", "proteina": "legumi", "stagione": "estate", "tempo": 15, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 63, "nome": "Torta salata ricotta e spinaci", "proteina": "legumi", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "unico"},
    {"id": 64, "nome": "Burrito di pollo bbq", "proteina": "carne bianca", "stagione": "generico", "tempo": 180, "adatto_al_lavoro": False, "tipologia": "unico"},
    {"id": 65, "nome": "Avocado toast", "proteina": "uova", "stagione": "generico", "tempo": 15, "adatto_al_lavoro": False, "tipologia": "unico"},
    {"id": 66, "nome": "Uova sode", "proteina": "uova", "stagione": "generico", "tempo": 10, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 67, "nome": "Uova al tegamino", "proteina": "uova", "stagione": "generico", "tempo": 5, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 68, "nome": "Uova strapazzate", "proteina": "uova", "stagione": "generico", "tempo": 5, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 69, "nome": "Frittata uova e verdure", "proteina": "uova", "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 70, "nome": "Pollo alle mandorle", "proteina": "carne bianca", "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 71, "nome": "Pollo al limone", "proteina": "carne bianca", "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 72, "nome": "Involtini di pollo feta e prosciutto", "proteina": "carne bianca", "stagione": "generico", "tempo": 35, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 73, "nome": "Pollo ai ferri", "proteina": "carne bianca", "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 74, "nome": "Pollo alla salvia", "proteina": "carne bianca", "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 75, "nome": "Rolle di pollo in forno", "proteina": "carne bianca", "stagione": "generico", "tempo": 80, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 76, "nome": "Pollo arrosto", "proteina": "carne bianca", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 77, "nome": "Sovracosce di pollo arrosto", "proteina": "carne bianca", "stagione": "generico", "tempo": 100, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 78, "nome": "Pollo e verdure alla soia", "proteina": "carne bianca", "stagione": "generico", "tempo": 35, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 79, "nome": "Spiedini di pollo e verdure", "proteina": "carne bianca", "stagione": "generico", "tempo": 40, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 80, "nome": "Pollo peperoni e cumino", "proteina": "carne bianca", "stagione": "generico", "tempo": 40, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 81, "nome": "Hamburger di pollo", "proteina": "carne bianca", "stagione": "generico", "tempo": 5, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 82, "nome": "Salsiccia di pollo", "proteina": "carne bianca", "stagione": "generico", "tempo": 5, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 83, "nome": "Hamburger di manzo", "proteina": "carne rossa", "stagione": "generico", "tempo": 10, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 84, "nome": "Panino con hamburger di manzo", "proteina": "carne rossa", "stagione": "generico", "tempo": 15, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 85, "nome": "Spezzatino di manzo", "proteina": "carne rossa", "stagione": "generico", "tempo": 180, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 86, "nome": "Roastbeef", "proteina": "carne rossa", "stagione": "generico", "tempo": 80, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 87, "nome": "Polpettone", "proteina": "carne bianca", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 88, "nome": "Polpettone", "proteina": "carne rossa", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 89, "nome": "Polpettone", "proteina": "latticini", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 90, "nome": "Polpettone", "proteina": "uova", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 91, "nome": "Hummus di ceci", "proteina": "legumi", "stagione": "generico", "tempo": 10, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 92, "nome": "Salsiccia di pollo e fagioli", "proteina": "legumi", "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 93, "nome": "Salsiccia di pollo e fagioli", "proteina": "carne bianca", "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 94, "nome": "Salmone in padella", "proteina": "pesce", "stagione": "generico", "tempo": 20, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 95, "nome": "Orata al forno", "proteina": "pesce", "stagione": "generico", "tempo": 80, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 96, "nome": "Merluzzo impanato al forno", "proteina": "pesce", "stagione": "generico", "tempo": 60, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 97, "nome": "Soute di cozze", "proteina": "pesce", "stagione": "generico", "tempo": 25, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 98, "nome": "Totani e piselli", "proteina": "pesce", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 99, "nome": "Polpo e patate", "proteina": "pesce", "stagione": "generico", "tempo": 180, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 100, "nome": "Tonno in padella", "proteina": "pesce", "stagione": "generico", "tempo": 25, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 101, "nome": "Polpette di pollo", "proteina": "carne bianca", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 102, "nome": "Polpette di manzo", "proteina": "carne rossa", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 103, "nome": "Polpette di ricotta", "proteina": "latticini", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 104, "nome": "Polpette di pesce", "proteina": "pesce", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 105, "nome": "Polpette di ceci", "proteina": "legumi", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 106, "nome": "Pollo al curry", "proteina": "carne bianca", "stagione": "generico", "tempo": 60, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 107, "nome": "Vitello tonnato", "proteina": "carne rossa", "stagione": "generico", "tempo": 80, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 108, "nome": "Calamari ripieni", "proteina": "pesce", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 109, "nome": "Seppie e piselli", "proteina": "pesce", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 110, "nome": "Polpette tonno e ricotta", "proteina": "pesce", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 111, "nome": "Zucchine ripiene manzo", "proteina": "carne rossa", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 112, "nome": "Zucchine ripiene pollo", "proteina": "carne bianca", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 113, "nome": "Polpette di patate", "proteina": "latticini", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 114, "nome": "Frittata di patate", "proteina": "uova", "stagione": "generico", "tempo": 35, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 115, "nome": "Frittata di zucchine", "proteina": "uova", "stagione": "generico", "tempo": 35, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 116, "nome": "Salmone in forno", "proteina": "pesce", "stagione": "generico", "tempo": 40, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 117, "nome": "Polpo alla luciana", "proteina": "pesce", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 118, "nome": "Polpette di zucchine", "proteina": "latticini", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 119, "nome": "Feta in forno", "proteina": "latticini", "stagione": "generico", "tempo": 45, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 120, "nome": "Rotolo di frittata farcito", "proteina": "uova", "stagione": "generico", "tempo": 60, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 121, "nome": "Rotolo di frittata farcito", "proteina": "latticini", "stagione": "generico", "tempo": 60, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 122, "nome": "Rotolo di frittata farcito", "proteina": "carne rossa", "stagione": "generico", "tempo": 60, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 123, "nome": "Melanzane alla pizzaiola", "proteina": "latticini", "stagione": "generico", "tempo": 40, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 124, "nome": "Nugget di pollo in forno", "proteina": "carne bianca", "stagione": "generico", "tempo": 50, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 125, "nome": "Crepes di spinaci con philadelphia e salmone", "proteina": "pesce", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 126, "nome": "Crepes di spinaci con philadelphia e salmone", "proteina": "latticini", "stagione": "generico", "tempo": 30, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 127, "nome": "Trippa", "proteina": "carne rossa", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 128, "nome": "Gamberoni", "proteina": "pesce", "stagione": "generico", "tempo": 35, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 129, "nome": "Fettine di manzo", "proteina": "carne rossa", "stagione": "generico", "tempo": 10, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 130, "nome": "Bollito", "proteina": "carne rossa", "stagione": "inverno", "tempo": 180, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 131, "nome": "Petti di pollo alla senape", "proteina": "carne bianca", "stagione": "generico", "tempo": 80, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 132, "nome": "Insalata di seppie", "proteina": "pesce", "stagione": "estate", "tempo": 25, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 133, "nome": "Caprese", "proteina": "latticini", "stagione": "estate", "tempo": 5, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 134, "nome": "Tomino", "proteina": "latticini", "stagione": "generico", "tempo": 1, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 135, "nome": "Fiocchi di latte", "proteina": "latticini", "stagione": "estate", "tempo": 1, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 136, "nome": "Polpette tonno e ricotta", "proteina": "latticini", "stagione": "generico", "tempo": 120, "adatto_al_lavoro": False, "tipologia": "secondo"},
    {"id": 137, "nome": "Bollito", "proteina": "carne bianca", "stagione": "inverno", "tempo": 180, "adatto_al_lavoro": True, "tipologia": "secondo"},
    {"id": 138, "nome": "Zucchine lesse / vapore", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 139, "nome": "Cavolfiore lesso / vapore", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 140, "nome": "Broccoli lessi / vapore", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 141, "nome": "Spinaci", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 142, "nome": "Piselli", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 143, "nome": "Fagiolini", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 144, "nome": "Pomodori", "proteina": None, "stagione": "generico", "tempo": 1, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 145, "nome": "Purè di patate", "proteina": None, "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 146, "nome": "Patate lesse / vapore", "proteina": None, "stagione": "generico", "tempo": 40, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 147, "nome": "Patate al forno", "proteina": None, "stagione": "generico", "tempo": 75, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 148, "nome": "Verdure al forno", "proteina": None, "stagione": "generico", "tempo": 75, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 149, "nome": "Peperonata", "proteina": None, "stagione": "generico", "tempo": 80, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 150, "nome": "Zucchine al pomodoro", "proteina": None, "stagione": "generico", "tempo": 40, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 151, "nome": "Zucchine in padella", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 152, "nome": "Zucchine alla soia", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 153, "nome": "Zucchine trifolate", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 154, "nome": "Insalata finocchi e arance", "proteina": None, "stagione": "generico", "tempo": 10, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 155, "nome": "Verdure gratinate", "proteina": None, "stagione": "generico", "tempo": 80, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 156, "nome": "Finocchi lessi / vapore", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 157, "nome": "Asparagi", "proteina": None, "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 158, "nome": "Verza in padella", "proteina": None, "stagione": "generico", "tempo": 40, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 159, "nome": "Minestrone", "proteina": None, "stagione": "generico", "tempo": 40, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 160, "nome": "Carote lesse", "proteina": None, "stagione": "generico", "tempo": 30, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 161, "nome": "Carote in padella", "proteina": None, "stagione": "generico", "tempo": 20, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 162, "nome": "Carote fresche", "proteina": None, "stagione": "generico", "tempo": 5, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 163, "nome": "Funghi", "proteina": None, "stagione": "generico", "tempo": 60, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 164, "nome": "Cavolfiore in padella", "proteina": None, "stagione": "generico", "tempo": 45, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 165, "nome": "Cavolfiore al forno", "proteina": None, "stagione": "generico", "tempo": 60, "adatto_al_lavoro": True, "tipologia": "contorno"},
    {"id": 166, "nome": "Insalata", "proteina": None, "stagione": "generico", "tempo": 1, "adatto_al_lavoro": True, "tipologia": "contorno"}
]
