services:
  app:
   # image: menu_app:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - menu-network
    depends_on:
      - db

  db:
    restart: always
    image: mysql:8.0
    environment:
      # Password per l'utente root (obbligatoria per il container)
      - MYSQL_ROOT_PASSWORD=rootpassword
      # Creazione del database all'avvio
      - MYSQL_DATABASE=menu_progetto
      # Creazione dell'utente dedicato
      - MYSQL_USER=menu
      - MYSQL_PASSWORD=menu
    ports:
      - "3306:3306"
    networks:
      - menu-network

networks:
  menu-network:
    driver: bridge
