services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_IP}:8000:8000"
    env_file:
      - .env
    networks:
      - menu-network

  popola-db:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 popola_db/popola_db.py
    env_file:
      - .env
    networks:
      - menu-network
    environment:
      - PYTHONPATH=/app

networks:
  menu-network:
    driver: bridge
